whitelist:
- src: task.py
docker:
  image: aleozlx/playbook-tensorflow:latest
  runtime: nvidia
  interactive: true
  impersonate: dynamic

num_samples: 10000000000
batch_size: 6553600

steps:
- name: 'Estimate pi using the "dartboard" method'
  action: main